### ISSUE TITLE
Error: hal2mafMP.py - ImportError: No module named hal.stats.halStats

### ISSUE THREAD

**Issue by sklages** [glennhickey/hal#43]
I compiled ragout from scratch, installed all requirements (hdf5,hal tools etc).
Running ragout on my data resulted in hal complaining:
```
[16:31:19] INFO: Starting Ragout v1.2
[16:31:19] INFO: Synteny block scale set to 'large'
[16:31:19] INFO: Extracting FASTA from HAL
[16:31:41] INFO: Converting HAL to MAF
Traceback (most recent call last):
  File "/package/sequencer/ragout/deps/hal/current/bin/hal2mafMP.py", line 23, in <module>
    from hal.stats.halStats import runParallelShellCommands
ImportError: No module named hal.stats.halStats
```

What did go wrong? There is no such module ... :-(
Any idea where to start looking?

best,
Sven

**Comment by glennhickey** [comment]
adding hal's *parent* directory to your PYTHONPATH may fix this.

**Comment by sklages** [comment]
Didn't solve it,

```
export PYTHONPATH=/path/to/hal:$PYTHONPATH

## /path/to/hal content
CODING_STYLE.txt  __init__.py     assemblyHub  extract     lod        randgen
LICENSE.txt       alignmentDepth  benchmarks   fasta       maf        stats
Makefile          allTests.py     bin          include.mk  modify     validate
README.md         analysis        chain        lib         mutations
README.pdf        api             extra        liftover    phyloP
```
results in the same error:

```
[12:26:31] INFO: Starting Ragout v1.2
[12:26:31] INFO: Synteny block scale set to 'large'
[12:26:31] INFO: Extracting FASTA from HAL
[12:26:57] INFO: Converting HAL to MAF
Traceback (most recent call last):
  File "/path/to/hal/bin/hal2mafMP.py", line 23, in <module>
    from hal.stats.halStats import runParallelShellCommands
ImportError: No module named hal.stats.halStats
[...]

```
Using its parent directory (`/path/to/`) resulted in the same error.

In `/path/to/hal`:
```
find . | grep halStats
./bin/halStats
./lib/halStats.h
./lib/halStats.a
./stats/halStats.py
./stats/impl/halStats.cpp
./stats/impl/halStatsMain.cpp
./stats/inc/halStats.h
./stats/halStatsMain.o
```

Probably sth. very obvious, but I don't see it ;-)

**Comment by sklages** [comment]
Yes, it is obvious :-)

The scripts expects `hal` to be located in an directory named `hal` (that's why it complained about `hal.stats.halStats` .. I didn't "see" that ..

I installed hal in a path like `/path/to/hal/1.8.16` ... I just linked `hal -> 1.8.16` and `hal.stats.halStats` becomes valid ..

So, yes, you were right. Thanks :-)
