### ISSUE TITLE
halPhyloPTrain.py problem with ref genome

### ISSUE THREAD

**Issue by evolgenomology** [glennhickey/hal#46]
Hi!

Running the command below I am getting some output (also pasted below), but also this error:
```
halPhyloPTrain.py ProgCact_run2.hal schizPom Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bed12.good halPhyloPTrain.ProgCact_run2.1.mod --numProc 12
Reading alignment from halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bed124d_I.maf ...
ERROR (msa_reorder_rows): name 'schizPom' missing from reorder list.
Traceback (most recent call last):
  File "/data2/bioProgs/progressiveCactus/submodules/hal/bin/halPhyloPTrain.py", line 279, in <module>
    sys.exit(main())
  File "/data2/bioProgs/progressiveCactus/submodules/hal/bin/halPhyloPTrain.py", line 276, in main
    computeModel(args)
  File "/data2/bioProgs/progressiveCactus/submodules/hal/bin/halPhyloPTrain.py", line 173, in computeModel
    computeAgMAFStats(options)
  File "/data2/bioProgs/progressiveCactus/submodules/hal/bin/halPhyloPTrain.py", line 138, in computeAgMAFStats
    options.outMafSS))
  File "/data2/bioProgs/progressiveCactus/submodules/hal/stats/halStats.py", line 27, in runShellCommand
    (command, sts))
RuntimeError: Command: msa_view -o SS -z --in-format MAF --aggregate None halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp*.maf > halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp.ss exited with non-zero status 1
```

There are four output files, but they seem temporary. At least from their name:
....halPhyloPTrain_temp_halPhyloPTrain.....
They look like this:
##maf version=1 scoring=N/A

a
s       schizPom.MTR    3359    1       +       20128   A
s       1000.1000refChr383      8515    1       -       11371   A
s       1001.1001refChr160      18508   1       +       27128   A
s       schizCryo.ACQJ03000138  360617  1       +       637338  A
s       schizOct.ABHY04000004   1054528 1       +       1884505 A

Any help highly appreciated.

Best

Philipp

**Comment by glennhickey** [comment]
It's been a while, but I remember msa_view (from the phyloP package) being
quite finicky, especially, I think, with respect to tree topology and maybe
even names.  @joelarmstrong <https://github.com/joelarmstrong> does this
ring a bell?

On Wed, Jun 29, 2016 at 12:13 PM, Philipp Schiffer <notifications@github.com

**Comment by joelarmstrong** [comment]
Hmm, from looking in the phast code it seems like that error means msa_view isn't finding a schizPom entry in the MAF, which seems a bit odd since it's in the example you showed.

I remember debugging some similar problems with msa_view with Ian (@ifiddes) a few months ago--but I can't remember the exact error message and can't find any relevant emails. Ian, do you remember running into something like this?

**Comment by ifiddes** [comment]
We ran into a similar, but different problem. As far as I remember I haven't seen the halPhyloPTrain script fail in this way before.

The issue we had involves stripping out comments from the maf. Here are the relevant lines in my script, with

**Comment by evolgenomology** [comment]
Hi guys!

Here is one question: In the input file with the tree I marked the 
schizPom as reference using the asterisk character *. Could this lead to 
problems downstream?

Cheers

Philipp

> Ian Fiddes <mailto:notifications@github.com>
> 30 June 2016 at 15:43
>
> We ran into a similar, but different problem. As far as I remember I 
> haven't seen the halPhyloPTrain script fail in this way before.
>
> The issue we had involves stripping out comments from the maf. Here 
> are the relevant lines in my script, with
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/glennhickey/hal/issues/46#issuecomment-229679676>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACEWbqM40p1tLrbTWNKHWjwb2h71njhcks5qQ9X0gaJpZM4JBTtK>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by ifiddes** [comment]
I don't think so, because the step it crashed on is just converting MAF to SS. I am wondering if it is the same problem - if you strip out the first two lines of each of those maf files, does the command work on its own?

**Comment by joelarmstrong** [comment]
How large are the maf files? Could you upload them somewhere? I'd be curious to see exactly where in the file msa_view starts having issues--that might determine whether it's a header problem or something else.

**Comment by evolgenomology** [comment]
Hi!
The file is here:
https://www.dropbox.com/s/irbstwp47ud2stz/ProgCact_run2.maf.gz?dl=0

Cheers

Philipp

Joel Armstrong wrote:

**Comment by evolgenomology** [comment]
@ifiddes after stripping the commented line from the temporary maf I get:
```
msa_view -o SS halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bed124d_II.maf > halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_halPhyloPTrain.ProgCact_run2.1_halPhyloPTrain_temp_Schizosaccharomyces_pombe.ASM294v2.22.cds.gff2bed124d_II.msaview
Unable to determine alignment format
```

**Comment by evolgenomology** [comment]
Hi!
Will check the size, but am sure I can wetransfer them. Will let you know in a bit.
P
Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.11.40&pv=9.3.1&source=email_footer_2]
On Thu, Jun 30, 2016 at 8:04 PM, Joel Armstrong <notifications@github.com> wrote:
How large are the maf files? Could you upload them somewhere? I'd be curious to see exactly where in the file msa_view starts having issues--that might determine whether it's a header problem or something else.

**Comment by evolgenomology** [comment]
Hi @glennhickey @ifiddes @joelarmstrong any news/ideas on this?

**Comment by joelarmstrong** [comment]
I've just noticed the problem, actually: the --aggregate parameter to msa_view is being set to "None" when it should be set to something like "schizPom,100,1000,...": i.e. a list of all the genomes in the alignment. I'm not quite sure exactly why that's being set to None, though. If there was an error getting that list it looks like it should've raised an exception much earlier.

Can you run `halStats --genomes <your hal file>` and tell me the output?

**Comment by evolgenomology** [comment]
Here it is:

~/bioProgs/hal/bin/halStats --genomes ProgCact_run2.hal
100 schizJap 1000 1001 schizCryo schizOct schizPom

> Joel Armstrong <mailto:notifications@github.com>
> 6 July 2016 at 02:43
>
> I've just noticed the problem, actually: the --aggregate parameter to 
> msa_view is being set to "None" when it should be set to something 
> like "schizPom,100,1000,...": i.e. a list of all the genomes in the 
> alignment. I'm not quite sure exactly why that's being set to None, 
> though. If there was an error getting that list it looks like it 
> should've raised an exception much earlier.
>
> Can you run |halStats --genomes <your hal file>| and tell me the output?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/glennhickey/hal/issues/46#issuecomment-230643296>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACEWbrnMGEVLUrllrXWGZuaTN8S5n2Msks5qSvpKgaJpZM4JBTtK>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by joelarmstrong** [comment]
Oops, my apologies, after looking at the commit log, this is actually caused by a bug that was fixed a few months back in this commit:

https://github.com/glennhickey/hal/commit/9b69387c8aa2c8e61a1c7c7f2e3af60b779c9868

I guess none of us recognized the symptom. If you update to the latest hal master branch, or the latest progressiveCactus, hopefully this issue will go away.

**Comment by evolgenomology** [comment]
Hi!

Thanks a lot. Using the halPhyloPTrain inside hal does indeed work. Great.
However, just for a test I pulled the latest progressiveCactus and 
tested. Doesn't work. So maybe there is a version conflict?

Cheers

Philipp

> Joel Armstrong <mailto:notifications@github.com>
> 7 July 2016 at 05:56
>
> Oops, my apologies, after looking at the commit log, this is actually 
> caused by a bug that was fixed a few months back in this commit:
>
> 9b69387 
> <https://github.com/glennhickey/hal/commit/9b69387c8aa2c8e61a1c7c7f2e3af60b779c9868>
>
> I guess none of us recognized the symptom. If you update to the latest 
> hal master branch, or the latest progressiveCactus, hopefully this 
> issue will go away.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/glennhickey/hal/issues/46#issuecomment-230979122>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACEWblwkrj-vxg2uQcai9GQ3XoYCLy0Tks5qTIb-gaJpZM4JBTtK>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by evolgenomology** [comment]
Hi @glennhickey @joelarmstrong @ifiddes thanks for all your help with this.
