### ISSUE TITLE
*** glibc detected *** halSnps: double free or corruption (fasttop): 0x00000000029a5fb0 ***

### ISSUE THREAD

**Issue by mjfi2sb3** [glennhickey/hal#49]
Hi,

I am getting the following error when I run halSnp.

######################
*** glibc detected *** halSnps: double free or corruption (fasttop): 0x00000000029a5fb0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3462875f4e]
/lib64/libc.so.6[0x3462878cad]
halSnps[0x471302]
halSnps[0x46defd]
halSnps[0x437fd1]
halSnps[0x43ce56]
halSnps[0x409867]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x346281ed5d]
halSnps[0x4068c9]
======= Memory map: ========
00400000-00725000 r-xp 00000000 00:37 225086                             /data/snapdragon/bougous/packages/progressiveCactus/submodules/hal/bin/halSnps
00924000-00930000 rw-p 00324000 00:37 225086                             /data/snapdragon/bougous/packages/progressiveCactus/submodules/hal/bin/halSnps
00930000-0094b000 rw-p 00000000 00:00 0 
02407000-0600c000 rw-p 00000000 00:00 0                                  [heap]
32b9600000-32b9682000 r-xp 00000000 00:33 14240698                       /cbrc/software/anaconda/v2.1.0a.app/lib/libm-2.5.so
32b9682000-32b9881000 ---p 00082000 00:33 14240698                       /cbrc/software/anaconda/v2.1.0a.app/lib/libm-2.5.so
32b9881000-32b9882000 r--p 00081000 00:33 14240698                       /cbrc/software/anaconda/v2.1.0a.app/lib/libm-2.5.so
32b9882000-32b9883000 rw-p 00082000 00:33 14240698                       /cbrc/software/anaconda/v2.1.0a.app/lib/libm-2.5.so
3462000000-3462020000 r-xp 00000000 00:10 339401                         /lib64/ld-2.12.so
346221f000-3462220000 r--p 0001f000 00:10 339401                         /lib64/ld-2.12.so
3462220000-3462221000 rw-p 00020000 00:10 339401                         /lib64/ld-2.12.so
3462221000-3462222000 rw-p 00000000 00:00 0 
3462800000-346298a000 r-xp 00000000 00:10 339406                         /lib64/libc-2.12.so
346298a000-3462b8a000 ---p 0018a000 00:10 339406                         /lib64/libc-2.12.so
3462b8a000-3462b8e000 r--p 0018a000 00:10 339406                         /lib64/libc-2.12.so
3462b8e000-3462b8f000 rw-p 0018e000 00:10 339406                         /lib64/libc-2.12.so
3462b8f000-3462b94000 rw-p 00000000 00:00 0 
3462c00000-3462c17000 r-xp 00000000 00:10 339412                         /lib64/libpthread-2.12.so
3462c17000-3462e17000 ---p 00017000 00:10 339412                         /lib64/libpthread-2.12.so
3462e17000-3462e18000 r--p 00017000 00:10 339412                         /lib64/libpthread-2.12.so
3462e18000-3462e19000 rw-p 00018000 00:10 339412                         /lib64/libpthread-2.12.so
3462e19000-3462e1d000 rw-p 00000000 00:00 0 
3463800000-3463807000 r-xp 00000000 00:10 339414                         /lib64/librt-2.12.so
3463807000-3463a06000 ---p 00007000 00:10 339414                         /lib64/librt-2.12.so
3463a06000-3463a07000 r--p 00006000 00:10 339414                         /lib64/librt-2.12.so
3463a07000-3463a08000 rw-p 00007000 00:10 339414                         /lib64/librt-2.12.so
3464c00000-3464c16000 r-xp 00000000 00:10 339466                         /lib64/libgcc_s-4.4.7-20120601.so.1
3464c16000-3464e15000 ---p 00016000 00:10 339466                         /lib64/libgcc_s-4.4.7-20120601.so.1
3464e15000-3464e16000 rw-p 00015000 00:10 339466                         /lib64/libgcc_s-4.4.7-20120601.so.1
3467000000-34670e8000 r-xp 00000000 00:10 339468                         /usr/lib64/libstdc++.so.6.0.13
34670e8000-34672e8000 ---p 000e8000 00:10 339468                         /usr/lib64/libstdc++.so.6.0.13
34672e8000-34672ef000 r--p 000e8000 00:10 339468                         /usr/lib64/libstdc++.so.6.0.13
34672ef000-34672f1000 rw-p 000ef000 00:10 339468                         /usr/lib64/libstdc++.so.6.0.13
34672f1000-3467306000 rw-p 00000000 00:00 0 
2b29ce930000-2b29ce931000 rw-p 00000000 00:00 0 
2b29ce938000-2b29ce94e000 r-xp 00000000 00:33 14250015                   /cbrc/software/anaconda/v2.1.0a.app/lib/libz.so.1.2.8
2b29ce94e000-2b29ceb4d000 ---p 00016000 00:33 14250015                   /cbrc/software/anaconda/v2.1.0a.app/lib/libz.so.1.2.8
2b29ceb4d000-2b29ceb4e000 rw-p 00015000 00:33 14250015                   /cbrc/software/anaconda/v2.1.0a.app/lib/libz.so.1.2.8
2b29ceb70000-2b29cebf8000 rw-p 00000000 00:00 0 
2b29d0000000-2b29d0021000 rw-p 00000000 00:00 0 
2b29d0021000-2b29d4000000 ---p 00000000 00:00 0 
7fff6a7c8000-7fff6a7de000 rw-p 00000000 00:00 0                          [stack]
7fff6a800000-7fff6a801000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by muffato** [comment]
Got the same error on my installations (RHEL7+gcc5 and Ubuntu 14.04+gcc4.8) and the HAL file computed from the example sequences

**Comment by joelarmstrong** [comment]
@muffato: do you have the latest master branch of hal? I ran into this as well a few months ago, and [came up with a fix](https://github.com/ComparativeGenomicsToolkit/hal/commit/fb18d1fabfd5d69c217c8e8146f0b5ce53f70e74) (at least for the crash I was running into!)

**Comment by muffato** [comment]
I was initially on 4d5002ec (Nov 2016), which the git submodule is pointing at, but I switched to master for the other pull-request, which is after your fix, and it's still failing.

**Comment by muffato** [comment]
Ah, no, wait. It only fails when called on two ancestral genomes
```
(gdb) run out.hal Anc0 Anc2
Starting program: /home/matthieu/src/local/cactus/bin/halSnps out.hal Anc0 Anc2

Program received signal SIGSEGV, Segmentation fault.
hal::DefaultColumnIterator::getTree (this=0xea0870) at impl/defaultColumnIterator.cpp:633
633         const Genome *genome = sequence->getGenome();
(gdb) bt
#0  hal::DefaultColumnIterator::getTree (this=0xea0870) at impl/defaultColumnIterator.cpp:633
Python Exception <class 'IndexError'> list index out of range: 
#1  0x0000000000408253 in countSnps (refGenome=refGenome@entry=0x9b81c0, targetGenomes=std::set with 1 elements, start=start@entry=0, length=length@entry=541095, doDupes=true, 
    refTsvStream=..., numSnps=numSnps@entry=0x7fffffffd030, numOrthologousPairs=numOrthologousPairs@entry=0x7fffffffd060, unique=unique@entry=false, minSpeciesForSnp=minSpeciesForSnp@entry=1)
    at impl/halSnps.cpp:388
#2  0x00000000004063fe in main (argc=<optimized out>, argv=<optimized out>) at impl/halSnps.cpp:184
```

but it works on extant genome vs ancestral genome, and extant genome vs extant genome

**Comment by joelarmstrong** [comment]
Interesting. D'oh, there must be some weird assumption in there about the reference being a leaf genome. I'll see what I can find.
